site_name: Sparc Docs
site_url: https://sparc.internike.com/docs
theme: readthedocs
use_directory_urls: false
docs_dir: md_docs
site_dir: html_docs

nav:
    - Sparc overview: 
      - What is it & why?: index.md
    - Understanding Sparc :
      - 1. The file structure: file_structure.md
      - 2. Configuring your app: app_config.md
      - 3. The routing: routing.md
      - 4. MVC base classes: baseClasses.md
      - 5. Your MVC components: mvc.md
      - 6. The Assets Manager: assets_mgr.md
    - Available plugins:
      - Picoreact: picoreact.md
      - MessageBus lib: msgbus.md
      - Logger: logger.md
      - Minimizer: minimizer.md
    - A typical application:
      - Setting up a master controller: master_ctrl.md
      - Setting up a master template: master_template.md
      - Setting up your custom User class: user_class.md
      - Implemention your custom libraries: libs.md