site_name: Sparc Docs
site_url: https://sparc.internike.com/docs
theme: readthedocs
use_directory_urls: false
docs_dir: md_docs
site_dir: html_docs

nav:
    - Sparc overview: 
      - What is it & why?: index.md
    - Learn Sparc in five steps:
      - 1. Understand the file structure: file_structure.md
      - 2. Configure your app: app_config.md
      - 3. Understand the routing: routing.md
      - 4. Write your MVC components: mvc.md
      - 5. Use Assets Manager: assets_mgr.md
    - Available plugins:
      - MessageBus lib: msgbus.md
      - Picoreact: picoreact.md
